### ISSUE TITLE
Bit, Nibble, Byte, Word in DSL

### ISSUE THREAD

**Issue by DrAma999** [DrAma999/BitWiser#3]
Create a DSL similar to SwiftUI language using `resultBuilder`, that helps in create bit, byte, word with specific operation modifier.
Something similar to:
```
Byte {
  Bit(0)
  Bit(1)
  Bit(0)
  Bit(1)
} // will produce 000001010
.masked(0b0000_0000)
```
@samueleperricone what do you think? can it be useful?

**Comment by samueleperricone** [comment]
> Create a DSL similar to SwiftUI language using `resultBuilder`, that helps in create bit, byte, word with specific operation modifier. Something similar to:
> 
> ```
> Byte {
>   Bit(0)
>   Bit(1)
>   Bit(0)
>   Bit(1)
> } // will produce 000001010
> .masked(0b0000_0000)
> ```
> 
> @samueleperricone what do you think? can it be useful?

Maybe composing a byte is less useful than creating byte array. in general yes, its a declarative approach and makes the code more readable and easier to change.

About byte array I often compose packets by joining bytes like:

```
[UInt8]([
   [0x01],
   mixOfBytes,
   [UInt8](repeating: 0xFF, 8)
].joined())
```

this could be improved with 

```
typealias ByteArray = [UInt8]

ByteArray {
     0xFF
     mixOfBytes
     [UInt8](repeating: 0xFF, 8)
}
```

**Comment by DrAma999** [comment]
It totally makes sense. I think that not only will improve readiness but will make easier and more coherent visually to use it in a full SwiftUI application. 
I will give it a shot, let's see if it works well

**Comment by DrAma999** [comment]
See [PR](https://github.com/DrAma999/BitWiser/pull/4) draft @samueleperricone   ;-)

**Comment by codingspark** [comment]
@DrAma999 After the PR is merged you could add your project [here](https://github.com/carson-katri/awesome-result-builders)
